spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.64.5
    port: 5672
    username: admin
    password: admin
  
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
zuul:  retryable: true
  
hystrix:
  command:
    defaul:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  
#ribbon:
#  ConnectTimeout: 1000
#  ReadTimeout: 1000
#  MaxAutoRetriesNextServer: 1
#  MaxAutoRetries: 1

#缺省配置 可以不写
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
